Implement `ragged_to_2darray` and `matrix_to_ragged`
Cloud-Drift/clouddrift pull request #158
Opened 2023-04-10 18:14 UTC by milancurcic

Notice the name `matrix_to_ragged` which warrants some discussion.

`2darray_to_ragged` is not a valid Python name, thus the "matrix". However, this makes it inconsistent with `ragged_to_2darray`.

One alternative is to call them `ragged_to_matrix` and `matrix_to_ragged` which makes them consistent. However, I'm not a big fan of the use of the word "matrix" here. Suggestions welcome.

Bumps the clouddrift version to 0.11.0.

Closes #152.

2023-04-10 19:22 UTC, selipot commented
`twod_to_ragged` and `ragged_to_twod`
`twodim_to_ragged` and `ragged_to_twodim`

2023-04-10 19:25 UTC, selipot requested changes

2023-04-10 19:25 UTC, selipot commented on clouddrift/analysis.py
> +    """Convert a 2d array to a ragged array. NaN values in the input array are
2d-> two-dimensional

2023-04-10 19:25 UTC, selipot commented on clouddrift/analysis.py
> +        A 2d array.
two-dimensional

2023-04-10 19:25 UTC, selipot commented on clouddrift/analysis.py
> +    """Convert a ragged array to a 2d array such that each contiguous segment
two-dimensional and elsewhere

2023-04-10 20:16 UTC, philippemiron commented
`data2d_to_ragged` and `ragged_to_data2d` maybe?

2023-04-11 18:24 UTC, milancurcic commented
I thought some more about this and have a new preferred name. Here are my ranked preferences:

1. `ragged_to_regular` and `regular_to_ragged`
2. `ragged_to_matrix` and `matrix_to_ragged`
3. `ragged_to_data2d` and `data2d_to_ragged`
4. `ragged_to_twodim` and `twodim_to_ragged`
5. `ragged_to_twod` and `twod_to_ragged`

Let me know your ranked preferences.

2023-04-11 20:11 UTC, philippemiron commented
1, 3, 2, 4, 5.

2023-04-11 20:16 UTC, selipot commented
> I thought some more about this and have a new preferred name. Here are my ranked preferences:
> 
> 1. `ragged_to_regular` and `regular_to_ragged`
> 2. `ragged_to_matrix` and `matrix_to_ragged`
> 3. `ragged_to_data2d` and `data2d_to_ragged`
> 4. `ragged_to_twodim` and `twodim_to_ragged`
> 5. `ragged_to_twod` and `twod_to_ragged`
> 
> Let me know your ranked preferences.

I like 1, let's go for it.

2023-04-11 21:20 UTC, merged